# Generated by Django 4.2.11 on 2025-08-06 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.asiento'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('vuelo', 'asiento'), name='reserva_asiento_unico_por_vuelo'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('vuelo', 'pasajero'), name='reserva_pasajero_unico_por_vuelo'),
        ),
    ]
